Repository Juarpla/med-connect, pull requests merged in 2024-07, with the labels that each got.

#1 appointmentsController-tests
  package.json
  tests/appointmentsController.test.js
  tests/doctors.test.json
  tests/doctorsController.test.js
  tests/medicalRecordsController.test.js
  tests/patients.test.json
  tests/patientsController.test.js
Labels: enhancement

#2 Fix swagger in dev environment
  docs/swagger/index.js
  docs/swagger/swagger.json
  docs/swagger/swaggerSetup.js
  package.json
  src/controllers/appointmentsController.js
  src/controllers/authController.js
  src/controllers/doctorsController.js
  src/controllers/medicalRecordsController.js
  src/controllers/patientsController.js
  src/controllers/prescriptionsController.js
  src/routes/appointments.js
  src/routes/index.js
  src/routes/patients.js
  src/routes/swaggerRoutes.js
  src/server.js
  src/swagger.js
Labels: bug

#9 Fix swagger in dev environment part 2
  docs/swagger/index.js
Labels: bug

#3 Add linter and formatter
  .eslintrc.json
  .prettierrc
  docs/swagger/index.js
  docs/swagger/swagger.json
  package.json
  src/controllers/appointmentsController.js
  src/controllers/authController.js
  src/controllers/doctorsController.js
  src/controllers/medicalRecordsController.js
  src/controllers/patientsController.js
  src/controllers/prescriptionsController.js
  src/models/Appointment.js
  src/models/Doctor.js
  src/models/MedicalRecord.js
  src/models/Patient.js
  src/models/Prescription.js
  src/models/User.js
  src/routes/appointments.js
  src/routes/auth.js
  src/routes/doctors.js
  src/routes/index.js
  src/routes/medicalRecords.js
  src/routes/patients.js
  src/routes/prescriptions.js
  src/server.js
  tests/appointmentsController.test.js
  tests/doctorsController.test.js
  tests/medicalRecordsController.test.js
  tests/patientsController.test.js
Labels: enhancement

#4 Set configuration for Auth2 login
  docs/swagger/index.js
  docs/swagger/swagger.json
  package.json
  src/controllers/authController.js
  src/controllers/homeController.js
  src/models/User.js
  src/routes/auth.js
  src/routes/index.js
  src/server.js
  src/utils/authHelpers.js
  src/utils/helpers.js
  src/utils/responseConfig.js
Labels: enhancement

#16 doctor controller test
  tests/doctorsController.test.js
Labels: enhancement

#18 medical record test
  tests/medicalRecordsController.test.js
Labels: enhancement

#17 patient controller test
  tests/patientsController.test.js
Labels: enhancement

#13 Set protected routes by OAuth2 - Part 1
  src/routes/appointments.js
  src/routes/patients.js
  src/utils/authHelpers.js
Labels: enhancement

#11 completed CRUD operations for MedicalRecords
  docs/api/medicalRecords.rest
  docs/swagger/swagger.json
  src/controllers/medicalRecordsController.js
  src/database/appointments.json
  src/database/doctors.json
  src/database/medicalRecords.json
  src/database/patients.json
  src/routes/medicalRecords.js
Labels: enhancement

#10 Set configuration to use OAuth logout
  docs/swagger/swagger.json
  src/controllers/authController.js
  src/controllers/homeController.js
  src/routes/index.js
Labels: enhancement

#14 Set validation: Patients CRUD
  docs/swagger/swagger.json
  package.json
  src/controllers/patientsController.js
  src/middleware/authMiddleware.js
  src/middleware/validationMiddleware.js
  src/routes/patients.js
  src/utils/validation.js
  src/validations/checkDataHelper.js
  src/validations/mongoIdValidation.js
  src/validations/patientValidation.js
Labels: enhancement

#19 doctor oauth and CRUD
  docs/swagger/swagger.json
  src/controllers/doctorsController.js
  src/routes/doctors.js
Labels: enhancement

#20 Set protected routes by OAuth - Part 2 - medicalRecords
  src/routes/medicalRecords.js
Labels: enhancement

#24 Medical records validation
  docs/swagger/swagger.json
  src/controllers/doctorsController.js
  src/controllers/medicalRecordsController.js
  src/routes/doctors.js
  src/routes/medicalRecords.js
Labels: enhancement

#25 Set validation appointments crud
  docs/swagger/swagger.json
  src/controllers/appointmentsController.js
  src/controllers/doctorsController.js
  src/controllers/medicalRecordsController.js
  src/routes/appointments.js
  src/routes/doctors.js
  src/routes/medicalRecords.js
  src/routes/patients.js
  src/validations/appointmentValidation.js
  src/validations/medicalRecordsValidation.js
  tests/doctorsController.test.js
  tests/medicalRecordsController.test.js
  tests/patientsController.test.js
Labels: bug, enhancement

#30 29 Fix hide endpoints no ready
  docs/swagger/swagger.json
  src/controllers/prescriptionsController.js
Labels: bug, invalid

#31 28 Fix validation appointment collection
  docs/swagger/swagger.json
  src/controllers/appointmentsController.js
  src/validations/appointmentValidation.js
Labels: bug

#32 27 Fix validation doctor collection
  docs/swagger/swagger.json
  src/controllers/doctorsController.js
  src/models/Doctor.js
  src/validations/doctorValidation.js
Labels: bug

#33 12 Fix misspelling function name
  src/server.js
  src/utils/index.js
Labels: invalid

#35 add readme and favicon config
  README.md
  package.json
  public/favicon.ico
  src/server.js
Labels: enhancement
